-- Esquema mínimo y datos de prueba para AsistenciaRepositoryAdapterTest.

CREATE TABLE semillero_integrante (
    id           BIGINT PRIMARY KEY,
    id_semillero BIGINT NOT NULL,
    nombres      VARCHAR(100) NOT NULL,
    apellidos    VARCHAR(100) NOT NULL,
    cedula       VARCHAR(15) NOT NULL,
    activo       BOOLEAN NOT NULL
);
CREATE TABLE actividad_cientifica (id_actividad BIGINT PRIMARY KEY, nombre VARCHAR(200) NOT NULL);
CREATE TABLE sesion_semillero (
    id_sesion           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_semillero        BIGINT NOT NULL,
    id_actividad        BIGINT,
    titulo              VARCHAR(200) NOT NULL,
    fecha               DATE NOT NULL,
    fecha_creacion      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP
);
CREATE TABLE asistencia_sesion (
    id_sesion     BIGINT NOT NULL,
    id_integrante BIGINT NOT NULL,
    estado        VARCHAR(20) NOT NULL,
    PRIMARY KEY (id_sesion, id_integrante)
);

INSERT INTO actividad_cientifica VALUES (1, 'Seminarios'), (2, 'Talleres');

-- Semillero 1: Ana y Beto activos, Carla retirada. Semillero 2: Dora.
INSERT INTO semillero_integrante VALUES
(1, 1, 'Ana',   'Zapata', '111', TRUE),
(2, 1, 'Beto',  'Arias',  '222', TRUE),
(3, 1, 'Carla', 'Mejía',  '333', FALSE),
(4, 2, 'Dora',  'Ruiz',   '444', TRUE);
