-- Esquema mínimo para las pruebas de solicitudes de acceso y tokens de cuenta (H2, modo PostgreSQL).

CREATE TABLE unidad_academica (id_unidad BIGINT PRIMARY KEY, nombre VARCHAR(200) NOT NULL);
INSERT INTO unidad_academica VALUES (1, 'Facultad de Ingeniería');

CREATE TABLE solicitud_acceso (
    id_solicitud        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres             VARCHAR(100) NOT NULL,
    apellidos           VARCHAR(100) NOT NULL,
    cedula              VARCHAR(15)  NOT NULL,
    correo              VARCHAR(150) NOT NULL,
    id_unidad_academica BIGINT,
    justificacion       TEXT         NOT NULL,
    estado              VARCHAR(30)  NOT NULL,
    token_hash          VARCHAR(64),
    token_expira        TIMESTAMP WITH TIME ZONE,
    envios_verificacion INTEGER      NOT NULL DEFAULT 0,
    ultimo_envio        TIMESTAMP WITH TIME ZONE,
    ip_origen           VARCHAR(64),
    fecha_creacion      TIMESTAMP WITH TIME ZONE NOT NULL,
    fecha_verificacion  TIMESTAMP WITH TIME ZONE,
    id_revisor          BIGINT,
    fecha_revision      TIMESTAMP WITH TIME ZONE,
    motivo_rechazo      TEXT,
    bloqueada           BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uq_solicitud_token ON solicitud_acceso (token_hash);

CREATE TABLE token_cuenta (
    id_token       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario     BIGINT      NOT NULL,
    token_hash     VARCHAR(64) NOT NULL UNIQUE,
    origen         VARCHAR(20) NOT NULL,
    expira         TIMESTAMP WITH TIME ZONE NOT NULL,
    usado          BOOLEAN     NOT NULL DEFAULT FALSE,
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
